SET DATABASE SQL SYNTAX ORA TRUE;
DROP SCHEMA IF EXISTS TEST CASCADE;

CREATE SCHEMA TEST;

DROP SEQUENCE IF EXISTS SEQ_T_PRODUCT;

DROP TABLE IF EXISTS T_PRODUCT;

CREATE SEQUENCE SEQ_T_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE T_PRODUCT
(
"TECH_ID" NUMBER(5, 0) NOT NULL,
"CODE" NUMBER(5, 0) NOT NULL,
"DESCRIPTION" VARCHAR2(200),
PRIMARY KEY("TECH_ID")
)
